http://localhost:3000

###

POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password123",
    "username": "genericusername"
}

###
# @name login

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password123"
}

###

GET http://localhost:3000/api/v1/auth/me
Cookie: {{login.response.headers.Set-Cookie}}

###

POST http://localhost:3000/api/v1/logout
Content-Type: application/json

###

POST http://localhost:3000/api/v1/auth/workouts
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "date": "2025-06-15",
    "name": "hiking with eszter",
    "notes": "skocjan cave system was awesome part two"
}

###

GET http://localhost:3000/api/v1/auth/workouts
Cookie: {{login.response.headers.Set-Cookie}}

###

GET http://localhost:3000/api/v1/auth/workouts/70a6c0c0-a70e-4f43-a6ae-efd7b2da2ccd
Cookie: {{login.response.headers.Set-Cookie}}

###

PUT http://localhost:3000/api/v1/auth/workouts/7922bfd8-d5e0-4c79-a2dc-4376eff75ccf
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
   "name": "complete new workout name"
}
###

DELETE http://localhost:3000/api/v1/auth/workouts/70a6c0c0-a70e-4f43-a6ae-efd7b2da2ccd
Cookie: {{login.response.headers.Set-Cookie}}

###

POST http://localhost:3000/api/v1/auth/exercises
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "name": "jogging",
    "category": "cardio"
}

###

GET http://localhost:3000/api/v1/auth/workouts/5a5fc8e2-80b3-43f8-ab45-bddcc8f627a0/exercises/
Cookie: {{login.response.headers.Set-Cookie}}

###

GET http://localhost:3000/api/v1/auth/exercises/b95db58e-a35d-430c-8b99-739fb69c6b5b
Cookie: {{login.response.headers.Set-Cookie}}


###

POST http://localhost:3000/api/v1/auth/workouts/7bf2134c-793f-4aee-9b6b-a29980d9b027/exercises
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "name": "hanky panky",
    "category": ":)))"
}

###

GET http://localhost:3000/api/v1/auth/workouts/70a6c0c0-a70e-4f43-a6ae-efd7b2da2ccd/exercises

Cookie: {{login.response.headers.Set-Cookie}}

###

DELETE http://localhost:3000/api/v1/auth/workouts/7bf2134c-793f-4aee-9b6b-a29980d9b027
Cookie: {{login.response.headers.Set-Cookie}}

###

GET http://localhost:3000/api/v1/auth/workouts/fd5093bd-997c-4b42-92dd-73320d626177/overview

Cookie: {{login.response.headers.Set-Cookie}}

###

POST http://localhost:3000/api/v1/auth/workouts/7bf2134c-793f-4aee-9b6b-a29980d9b027/exercises/071a2b38-1678-4cef-8391-b74208c40bae/sets
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "reps": 12,
    "weight": 5.6,
    "notes": "was okay"
}

###

DELETE http://localhost:3000/api/v1/auth/workouts/55e04db0-3ed5-4a65-8b92-d1d7361e3aaf/exercises/de8f8f3a-36c4-46aa-befc-b6f4e7bbb7eb
Cookie: {{login.response.headers.Set-Cookie}}


###

POST http://localhost:3000/api/v1/auth/completeWorkouts
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "workout": {
        "date": "2025-07-25",
        "name": "Push Day Workout",
        "notes": "Focus on chest, shoulders, and triceps"
    },
    "exercises": [
        {
            "name": "Bench Press",
            "category": "chest",
            "notes": "Keep form tight",
            "metric": "weight",
            "sets": [
                {
                    "reps": 8,
                    "metric_value": 80.0
                },
                {
                    "reps": 6,
                    "metric_value": 90.0
                },
                {
                    "reps": 4,
                    "metric_value": 100.0
                }
            ]
        },
        {
            "name": "Overhead Press",
            "category": "shoulders",
            "notes": "Focus on core stability",
            "metric": "weight",
            "sets": [
                {
                    "reps": 10,
                    "metric_value": 50.0
                },
                {
                    "reps": 8,
                    "metric_value": 55.0
                }
            ]
        },
        {
            "name": "Jogging",
            "category": "cardio",
            "notes": "Cardio finisher",
            "metric": "distance",
            "sets": [
                {
                    "reps": 1,
                    "metric_value": 22
                }
            ]
        }
    ]
}