http://localhost:3000

###

POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password123"
}

###
# @name login

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password123"
}

###

GET http://localhost:3000/api/v1/auth/me
Cookie: {{login.response.headers.Set-Cookie}}

###

POST http://localhost:3000/api/v1/logout
Content-Type: application/json

###

POST http://localhost:3000/api/v1/auth/workouts
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "date": "2025.05.15",
    "name": "spinning with eszter",
    "notes": "we ended up having burgers :("
}

###

GET http://localhost:3000/api/v1/auth/workouts
Cookie: {{login.response.headers.Set-Cookie}}

###

GET http://localhost:3000/api/v1/auth/workouts/7b20b747-3976-44ca-9982-3399a952a266
Cookie: {{login.response.headers.Set-Cookie}}

###

PUT http://localhost:3000/api/v1/auth/workouts/7b20b747-3976-44ca-9982-3399a952a266
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
   "name": "complete new workout name"
}
###

DELETE http://localhost:3000/api/v1/auth/workouts/68760fa2-6ee4-44a2-8167-047fb47ad359
Cookie: {{login.response.headers.Set-Cookie}}

###

POST http://localhost:3000/api/v1/auth/exercises
Cookie: {{login.response.headers.Set-Cookie}}
Content-Type: application/json

{
    "name": "jogging",
    "category": "cardio"
}
